on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy and Capture Output
        id: deploy
        run: |
          OUTPUT=$(cloudflare/wrangler-action@v3 pages deploy ./dist --project-name=panther-press)
          echo "deploy_output=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Extract URLs
        id: urls
        run: |
          DEPLOY_URL=$(echo '${{ steps.deploy.outputs.deploy_output }}' | grep -o 'https://[0-9a-f]\+\.panther-press\.pages\.dev')
          ALIAS_URL=$(echo '${{ steps.deploy.outputs.deploy_output }}' | grep -o 'https://[^[:space:]]*\.panther-press\.pages\.dev' | grep -v '[0-9a-f]\{8\}')
          echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
          echo "alias_url=$ALIAS_URL" >> $GITHUB_OUTPUT

      - name: Display URLs
        run: |
          echo "✨ Deployment URL: ${{ steps.urls.outputs.deploy_url }}"
          echo "✨ Alias URL: ${{ steps.urls.outputs.alias_url }}"