on:
  pull_request:
  push:
    branches-ignore:
      - keystatic
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    name: Deploy
    permissions:
      contents: read
      deployments: write
      pull-requests: write
      issues: write
    
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=panther-press --branch=${{ github.head_ref || github.ref_name }}
      - name: Create comment
        uses: actions/github-script@v7
        with:
          script: |
            if (${{ steps.deploy.outputs.stderr }}) {
              github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '## ❌ Deployment failed:\n ```${{ steps.deploy.outputs.stderr }}```'
                })
            }
            else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## ✅ Deploy successful!\n ✨ Deployment URL: ${{ steps.deploy.outputs.deployment-url }}\n✨ Alias URL: ${{ steps.deploy.outputs.pages-deployment-alias-url }}'
              })
            }
            