on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    name: Deploy
    permissions:
      contents: read
      deployments: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=panther-press
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract URLs
        id: urls
        run: |
          DEPLOY_URL=$(echo '${{ steps.deploy.outputs.command-output }}' | grep -o 'https://[0-9a-f]\+\.panther-press\.pages\.dev')
          ALIAS_URL=$(echo '${{ steps.deploy.outputs.command-output }}' | grep -o 'https://[^[:space:]]*\.panther-press\.pages\.dev' | grep -v '[0-9a-f]\{8\}')
          echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
          echo "alias_url=$ALIAS_URL" >> $GITHUB_OUTPUT
      - name: Display URLs
        run: |
          echo "✨ Deployment URL: ${{ steps.urls.outputs.deploy_url }}"
          echo "✨ Alias URL: ${{ steps.urls.outputs.alias_url }}"
      - name: Create comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✨ Deployment URL: ${{ steps.urls.outputs.deploy_url }}\n✨ Alias URL: ${{ steps.urls.outputs.alias_url }}'
            })